const btnHome = document.getElementById("btn-home")
const btnPerfil = document.getElementById("btn-perfil")
const btnFavoritos = document.getElementById("btn-favoritos")
const btnMensajes = document.getElementById("btn-mensajes")
const textHome = document.getElementById("home-text")
const textPerfil = document.getElementById("perfil-text")
const textFavoritos = document.getElementById("favoritos-text")
const textMensajes = document.getElementById("mensajes-text")
const iconHome = document.getElementById("home-icon")
const iconPerfil = document.getElementById("perfil-icon")
const iconFavoritos = document.getElementById("favoritas-icon")
const iconMensajes = document.getElementById("mensajes-icon")

